<?php
/**
 * This file acts as the "front controller" for CSScaffold.
 * DO NOT EDIT THIS FILE!
 *
 * It's fairly straightforward. It loads a config file, sets an include path,
 * chooses if to run the installer, and then runs CSScaffold. You
 * should be able to pull CSScaffold out and use it however you wish as
 * long as the config file is in the right format.
 *
 * @package CSScaffold
 */
 
# CSScaffold requires this constant
define('SCAFFOLD_DIR', dirname(__FILE__));

# Include the config file
include 'config.php';

# Set the include path
set_include_path(realpath($path['system']) . PATH_SEPARATOR . get_include_path());

# Include the main class
require 'core/CSScaffold.php';

# And we're off!
if(isset($_GET['request']))
{
	CSScaffold::run($_GET, $config, $path);
}