<?php
/**
 * This file acts as the "front controller" for CSScaffold.
 * DO NOT EDIT THIS FILE!
 *
 * It's fairly straightforward. It loads a config file, sets an include path,
 * chooses if to run the installer, and then runs CSScaffold. You
 * should be able to pull CSScaffold out and use it however you wish as
 * long as the config file is in the right format.
 *
 * @package CSScaffold
 */
define('SCAFFOLD_DIR', dirname(__FILE__));

# Include the config file
include 'config.php';

# Set error reporting. Debug setting overrides this later.
ini_set('display_errors', TRUE);
error_reporting(E_ALL & ~E_STRICT);

# Set the include path
set_include_path($path['system'] . PATH_SEPARATOR . get_include_path());

# Include the main class
require 'core/CSScaffold.php';

# And we're off!
if(isset($_GET['request']))
{
	CSScaffold::run($_GET, $config, $path);
}

# If there's no request, load the installer
elseif($install)
{
	header('Location: install/');
    exit();
}

# There's nothing to use... :(
else
{
	header('Location: /');
    exit();
}